version: "3.1"
services:
  frontend:
    image: node:14-alpine
    container_name: fan7_frontend
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./app
    command: ["sh", "+x", "./docker-entrypoint.sh"]
